import { project1, project2, project3, project4, project5, project6, project7, project8, project9, } from "@/public";

export const projectItems = [
   {
      id: 1,
      title: 'Fun',
      description: `Designing a new video-only dating app 💖 with Brian \nNorgard (ex-CPO-Tinder) and Farb Nivi.`,
      img: project1,
      href: "/project/fun",
      video: "/robinNoguier1.mp4",
      headingColor: "#D5DEDD",
      paraColor: "#fff",
      bgColor: "#3D6681",
      linkText: "open case study",
   },
   {
      id: 2,
      title: 'Esperanto',
      description: `My year long journey around the world to shine a light on creatives from 16 different countries.`,
      img: project2,
      href: "/project/esperanto",
      video: "/robinNoguier2.mp4",
      headingColor: "#FE3448",
      paraColor: "#0D0D0D",
      bgColor: "#F5F8FF",
      linkText: "open case study",
   },
   {
      id: 3,
      title: 'Blurr',
      description: `blurr aspires to be the best platform for creators to share their NFTs with the world.`,
      img: project3,
      href: "/project/blurr",
      video: "/robinNoguier3.mp4",
      headingColor: "#D2D2D2",
      paraColor: "#F6E3E8",
      bgColor: "#C2375A",
      linkText: "open case study",
   },
   {
      id: 4,
      title: 'Ueno',
      description: `I worked on client projects for companies like Redbull, Uber and Oculus, as well as the agency’s own brand.`,
      img: project4,
      href: "/project/ueno",
      video: "/robinNoguier4.mp4",
      headingColor: "#FFF794",
      paraColor: "#fff",
      bgColor: "#7AB9E0",
      linkText: "open case study",
   },
   {
      id: 5,
      title: 'Airbnb',
      description: `Describing the flow of athletes receiving their Airbnb credits for the next Olympic games. Also introducing the flow for creating an interview for each Olympian.`,
      img: project5,
      href: "/project/airbnb",
      video: "/robinNoguier5.mp4",
      headingColor: "#CCBA8E",
      paraColor: "#fff",
      bgColor: "#3D6681",
      linkText: "open case study",
   },
   {
      id: 6,
      title: 'Google',
      description: `With Factor SF I created a marketing site introducing Google Express’s voice activated shopping.`,
      img: project6,
      href: "/project/google",
      video: "/robinNoguier6.mp4",
      headingColor: "#FF6F64",
      paraColor: "#111111",
      bgColor: "#FFFFFF",
      linkText: "open case study",
   },
   {
      id: 7,
      title: 'SnickSnack',
      description: `Designing a new way to talk with close friends through audio and video aiming to build better friendships.`,
      img: project7,
      href: "/project/snickSnack",
      video: "/robinNoguier7.mp4",
      headingColor: "#66FFDE",
      paraColor: "#fff",
      bgColor: "#F27DB5",
      linkText: "open case study",
   },
   {
      id: 8,
      title: 'Iv-Skaya',
      description: `With Russian photographer Elena Iv-Skaya, I created a portfolio that matches her rich and colorful style.`,
      img: project8,
      href: "/project/iv-skaya",
      video: "/robinNoguier8.mp4",
      headingColor: "#FFF6E7",
      paraColor: "#FFF6E7",
      bgColor: "#FB1515",
      linkText: "open case study",
   },
   {
      id: 9,
      title: 'Eagle Films',
      description: `An online presence for Eagle Films, introducing the company, the movies, the team and their values to the world.`,
      img: project9,
      href: "/project/eagle-films",
      video: "/robinNoguier9.mp4",
      headingColor: "#B9966E",
      paraColor: "#fff",
      bgColor: "#153136",
      linkText: "open case study",
   },
];